theme: jekyll-theme-minimal
title: Matt Evitts | Software Engineering Intern
description: Software Engineering Intern with a strong interest in AI/ML engineering, data science, and technical solutions, specializing in generative AI and machine learning systems.
show_downloads: true
logo: https://github.com/mevitts.png
